openapi: 3.0.0
info:
  title: Yes or No
  version: 1.0.0
  description: Response with "Yes" if path contains /yes/ or "No" if path contains "/no/"
paths:
  /{head+}/yes/{tail+}:
    get:
      parameters:
        - name: head
          in: path
        - name: tail
          in: path
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        content:
          "*": "Yes!"
  /{head+}/no/{tail+}:
    get:
      parameters:
        - name: head
          in: path
        - name: tail
          in: path
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        content:
          "*": "No!"
